name: Deploy Bus App to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'bus/**'
      - '.github/workflows/deploy-bus.yml'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd bus
          npm ci

      - name: Build
        run: |
          cd bus
          npm run build

      - name: Add 404.html for SPA routing
        run: cp bus/build/index.html bus/build/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bus/build
          destination_dir: bus
          keep_files: true
